DECISION TREE

IMPORT IMPORATNT LIBRARY

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

 IMPORTING AND READING THE DATA

In [ ]:
df=pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

EXPLORATORY DATA ANALYSIS

In [ ]:
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [ ]:
df.tail()

company                  job     degree  salary_more_then_100k
11  facebook      sales executive    masters                      1
12  facebook     business manager  bachelors                      1
13  facebook     business manager    masters                      1
14  facebook  computer programmer  bachelors                      1
15  facebook  computer programmer    masters                      1

In [ ]:
df.shape

(16, 4)

In [ ]:
df.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [ ]:
df.info(

)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 640.0+ bytes


DATA PREPROCESSING

In [ ]:
indpvar=df.drop('salary_more_then_100k',axis='columns')
target=df['salary_more_then_100k']

In [ ]:
indpvar.head()

company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [ ]:
target.head()

0    0
1    0
2    1
3    1
4    0
Name: salary_more_then_100k, dtype: int64

In [ ]:
 le_company=LabelEncoder()
 le_job=LabelEncoder()
 le_degree=LabelEncoder()

In [ ]:
indpvar['company_n']=le_company.fit_transform(indpvar['company'])
indpvar['job_n']=le_company.fit_transform(indpvar['job'])
indpvar['degree_n']=le_company.fit_transform(indpvar['degree'])
indpvar.head()

company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [ ]:
indpvar_n=indpvar.drop(['company','job','degree'],axis='columns')
indpvar_n

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

TEST-TRAIN SPLIT

In [ ]:
indpvar_n_train,indpvar_n_test,target_train,target_test=train_test_split(indpvar_n,target,test_size=0.2)

DECISION TREE WITH CRITERION GINI INDEX

In [ ]:
clf_gini=DecisionTreeClassifier(criterion='gini',max_depth=3,random_state=0)
clf_gini.fit(indpvar_n_train,target_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

PREDICT THE TEST RESULTS

In [ ]:
Y_gini_pred=clf_gini.predict(indpvar_n_test)

CHECK ACCURACY SCORES

In [ ]:
print('model accuracy score with criterion gini index:{0:0.4f}'.format(accuracy_score(target_test,Y_gini_pred)))

model accuracy score with criterion gini index:0.7500


In [ ]:
Y_gini_pred_train=clf_gini.predict(indpvar_n_train)
Y_gini_pred_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [ ]:
print('training set accuracy score:{0:0.4f}'.format(accuracy_score(target_train,Y_gini_pred_train)))

training set accuracy score:0.9167


In [ ]:
print('Training set score: {:.4f}'.format(clf_gini.score(indpvar_n_train, target_train)))

print('Test set score: {:.4f}'.format(clf_gini.score(indpvar_n_test, target_test)))

Training set score: 0.9167
Test set score: 0.7500


DECISION TREE CLASSIFIER WITH CRITERION ENTROPY

In [ ]:
clf_en=DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)
clf_en.fit(indpvar_n_train,target_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [ ]:
y_pred_en=clf_en.predict(indpvar_n_test)
y_pred_en

array([1, 0, 0, 1])

ACCURACY SCORES

In [ ]:
print('model accuracy score with criterion entropy:{0:0.4f}'.format(accuracy_score(target_test,y_pred_en)))

model accuracy score with criterion entropy:0.7500


In [ ]:
y_pred_en_train=clf_en.predict(indpvar_n_train)
y_pred_en_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [ ]:
print('training set accuracy score:{0:0.4f}'.format(accuracy_score(target_train,y_pred_en_train)))

training set accuracy score:0.9167


In [ ]:
print('Training set score: {:.4f}'.format(clf_en.score(indpvar_n_train, target_train)))

print('Test set score: {:.4f}'.format(clf_en.score(indpvar_n_test, target_test)))

Training set score: 0.9167
Test set score: 0.7500
