#**<font color='blue'><b>Lab-02 Linear Regression With One Variable**

> Indented block





In the first part of the exercise, we're tasked with implementing linear regression with one variable to predict profits for a food truck. Suppose you are the CEO of a restaurant franchise and are considering different cities for opening a new outlet. The chain already has trucks in various cities and you have data for profits and populations from the cities.

**Let's start by importing some libraries and examining the data.**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from google.colab import files
files.upload()


Saving ex1data1.csv to ex1data1.csv


{'ex1data1.csv': b'6.1101,17.592\n5.5277,9.1302\n8.5186,13.662\n7.0032,11.854\n5.8598,6.8233\n8.3829,11.886\n7.4764,4.3483\n8.5781,12\n6.4862,6.5987\n5.0546,3.8166\n5.7107,3.2522\n14.164,15.505\n5.734,3.1551\n8.4084,7.2258\n5.6407,0.71618\n5.3794,3.5129\n6.3654,5.3048\n5.1301,0.56077\n6.4296,3.6518\n7.0708,5.3893\n6.1891,3.1386\n20.27,21.767\n5.4901,4.263\n6.3261,5.1875\n5.5649,3.0825\n18.945,22.638\n12.828,13.501\n10.957,7.0467\n13.176,14.692\n22.203,24.147\n5.2524,-1.22\n6.5894,5.9966\n9.2482,12.134\n5.8918,1.8495\n8.2111,6.5426\n7.9334,4.5623\n8.0959,4.1164\n5.6063,3.3928\n12.836,10.117\n6.3534,5.4974\n5.4069,0.55657\n6.8825,3.9115\n11.708,5.3854\n5.7737,2.4406\n7.8247,6.7318\n7.0931,1.0463\n5.0702,5.1337\n5.8014,1.844\n11.7,8.0043\n5.5416,1.0179\n7.5402,6.7504\n5.3077,1.8396\n7.4239,4.2885\n7.6031,4.9981\n6.3328,1.4233\n6.3589,-1.4211\n6.2742,2.4756\n5.6397,4.6042\n9.3102,3.9624\n9.4536,5.4141\n8.8254,5.1694\n5.1793,-0.74279\n21.279,17.929\n14.908,12.054\n18.959,17.054\n7.2182,4.88

In [ ]:
data =pd.read_csv('ex1data1.csv',names=['Population','Profit'])

In [ ]:
data.insert(0,"ones",1)

In [ ]:
print(data.head)

<bound method NDFrame.head of     ones  Population    Profit
0      1      6.1101  17.59200
1      1      5.5277   9.13020
2      1      8.5186  13.66200
3      1      7.0032  11.85400
4      1      5.8598   6.82330
..   ...         ...       ...
92     1      5.8707   7.20290
93     1      5.3054   1.98690
94     1      8.2934   0.14454
95     1     13.3940   9.05510
96     1      5.4369   0.61705

[97 rows x 3 columns]>


In [ ]:
cols=data.shape[1]
x=data.iloc[:,0:cols-1]
y=data.iloc[:,cols-1:cols]

In [ ]:
print(data.shape)

(97, 3)


In [ ]:
x=np.matrix(x.values)
y=np.matrix(y.values)
theta=np.matrix(np.array([0,0]))

In [ ]:
print(x)

[[ 1.      6.1101]
 [ 1.      5.5277]
 [ 1.      8.5186]
 [ 1.      7.0032]
 [ 1.      5.8598]
 [ 1.      8.3829]
 [ 1.      7.4764]
 [ 1.      8.5781]
 [ 1.      6.4862]
 [ 1.      5.0546]
 [ 1.      5.7107]
 [ 1.     14.164 ]
 [ 1.      5.734 ]
 [ 1.      8.4084]
 [ 1.      5.6407]
 [ 1.      5.3794]
 [ 1.      6.3654]
 [ 1.      5.1301]
 [ 1.      6.4296]
 [ 1.      7.0708]
 [ 1.      6.1891]
 [ 1.     20.27  ]
 [ 1.      5.4901]
 [ 1.      6.3261]
 [ 1.      5.5649]
 [ 1.     18.945 ]
 [ 1.     12.828 ]
 [ 1.     10.957 ]
 [ 1.     13.176 ]
 [ 1.     22.203 ]
 [ 1.      5.2524]
 [ 1.      6.5894]
 [ 1.      9.2482]
 [ 1.      5.8918]
 [ 1.      8.2111]
 [ 1.      7.9334]
 [ 1.      8.0959]
 [ 1.      5.6063]
 [ 1.     12.836 ]
 [ 1.      6.3534]
 [ 1.      5.4069]
 [ 1.      6.8825]
 [ 1.     11.708 ]
 [ 1.      5.7737]
 [ 1.      7.8247]
 [ 1.      7.0931]
 [ 1.      5.0702]
 [ 1.      5.8014]
 [ 1.     11.7   ]
 [ 1.      5.5416]
 [ 1.      7.5402]
 [ 1.      5.3077]
 [ 1.      7

In [ ]:
theta.shape

(1, 2)

In [ ]:
x.shape

(97, 2)

In [ ]:
y.shape

(97, 1)

In [ ]:
y_hat=x*theta.T
print(y_hat)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
error=np.power(y_hat-y,2)
print(error)

[[3.09478464e+02]
 [8.33605520e+01]
 [1.86650244e+02]
 [1.40517316e+02]
 [4.65574229e+01]
 [1.41276996e+02]
 [1.89077129e+01]
 [1.44000000e+02]
 [4.35428417e+01]
 [1.45664356e+01]
 [1.05768048e+01]
 [2.40405025e+02]
 [9.95465601e+00]
 [5.22121856e+01]
 [5.12913792e-01]
 [1.23404664e+01]
 [2.81409030e+01]
 [3.14462993e-01]
 [1.33356432e+01]
 [2.90445545e+01]
 [9.85080996e+00]
 [4.73802289e+02]
 [1.81731690e+01]
 [2.69101562e+01]
 [9.50180625e+00]
 [5.12479044e+02]
 [1.82277001e+02]
 [4.96559809e+01]
 [2.15854864e+02]
 [5.83077609e+02]
 [1.48840000e+00]
 [3.59592116e+01]
 [1.47233956e+02]
 [3.42065025e+00]
 [4.28056148e+01]
 [2.08145813e+01]
 [1.69447490e+01]
 [1.15110918e+01]
 [1.02353689e+02]
 [3.02214068e+01]
 [3.09770165e-01]
 [1.52998323e+01]
 [2.90025332e+01]
 [5.95652836e+00]
 [4.53171312e+01]
 [1.09474369e+00]
 [2.63548757e+01]
 [3.40033600e+00]
 [6.40688185e+01]
 [1.03612041e+00]
 [4.55679002e+01]
 [3.38412816e+00]
 [1.83912322e+01]
 [2.49810036e+01]
 [2.02578289e+00]
 [2.019525

In [ ]:
cost=np.sum(error)/(2*len(x))
cost

32.072733877455676

In [ ]:
def computeCost(x, y, theta):
    y_hat=x*theta.T
    inner=np.power(y_hat-y,2)
    return np.sum(inner)/(2*len(x))

    return cost

In [ ]:
def computeCost()

In [ ]:
computeCost(x,y,theta)

32.072733877455676

In [ ]:
tem=np.matrix(np.zeros(theta.shape))
print(tem)

[[0. 0.]]


**Lab-01(b) Linear Regression with multiple Variables**